In [2]:
import pandas as pd
import numpy as np

In [26]:
file_path = "/Users/godwinvasanthsamueldhinakar/EDA/F500.csv"

df= pd.read_csv(file_path,sep=';')
print('**************************************************')
print(df.info())

**************************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             500 non-null    int64
 1   rank           500 non-null    int64
 2   name           500 non-null    object
 3   employees      500 non-null    object
 4   previousrank   492 non-null    float64
 5   revenues       500 non-null    object
 6   revenuechange  500 non-null    object
 7   profits        500 non-null    object
 8   profitschange  500 non-null    object
 9   assets         500 non-null    object
 10  marketvalue    500 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 43.1+ KB
None

In [3]:
df.head(10)

,id,rank,name,employees,previousrank,revenues,revenuechange,profits,profitschange,assets,marketvalue
0,2,1,Walmart,"2,300,000",1.0,"$485,873",0.8%,"$13,643.0",-7.2%,"$198,825","$218,619"
1,3,2,Berkshire Hathaway,"367,700",4.0,"$223,604",6.1%,"$24,074.0",0.0%,"$620,854","$411,035"
2,4,3,Apple,"116,000",3.0,"$215,639",-7.7%,"$45,687.0",-14.4%,"$321,686","$753,718"
3,5,4,Exxon Mobil,"72,700",2.0,"$205,004",-16.7%,"$7,840.0",-51.5%,"$330,314","$340,056"
4,6,5,McKesson,"68,000",5.0,"$192,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
5,7,6,UnitedHealth Group,"230,000",6.0,"$184,840",17.7%,"$7,017.0",20.7%,"$122,810","$157,793"
6,8,7,CVS Health,"204,000",7.0,"$177,526",15.8%,"$5,317.0",1.5%,"$94,462","$81,310"
7,9,8,General Motors,"225,000",8.0,"$166,380",9.2%,"$9,427.0",-2.7%,"$221,690","$52,968"
8,10,9,AT&T,"268,540",10.0,"$163,786",11.6%,"$12,976.0",-2.8%,"$403,821","$255,679"
9,11,10,Ford Motor,"201,000",9.0,"$151,800",1.5%,"$4,596.0",-37.7%,"$237,951","$46,349"

In [27]:
df['revenues']=pd.to_numeric(df['revenues'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df['profits']=pd.to_numeric(df['profits'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df['assets']=pd.to_numeric(df['assets'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df['marketvalue']=pd.to_numeric(df['marketvalue'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df['employees']=pd.to_numeric(df['employees'].str.replace(',', ''),errors='coerce')
df['previousrank']=df['previousrank'].astype('Int64')
df[['revenuechange', 'profitschange']] = df[['revenuechange', 'profitschange']].apply(
    lambda col: pd.to_numeric(
        col.astype(str).str.replace('%', '', regex=False).replace('-', 'NaN'),
        errors='coerce'
    )
)
# df[['profitschange','assetschange','marketvaluechange']]=df[['profitschange','assetschange','marketvaluechange']].replace('%', '', regex=True).astype('float')
# df.drop(['id','revenues','profits','assets','marketvalue','previousrank','employees','profitschange','revenuechange'],axis=1,inplace=True)

In [28]:
df.head(10)

,id,rank,name,employees,previousrank,revenues,revenuechange,profits,profitschange,assets,marketvalue
0,2,1,Walmart,2300000,1,485873,0.8,13643.0,-7.2,198825,218619.0
1,3,2,Berkshire Hathaway,367700,4,223604,6.1,24074.0,0.0,620854,411035.0
2,4,3,Apple,116000,3,215639,-7.7,45687.0,-14.4,321686,753718.0
3,5,4,Exxon Mobil,72700,2,205004,-16.7,7840.0,-51.5,330314,340056.0
4,6,5,McKesson,68000,5,192487,6.2,2258.0,53.0,56563,31439.0
5,7,6,UnitedHealth Group,230000,6,184840,17.7,7017.0,20.7,122810,157793.0
6,8,7,CVS Health,204000,7,177526,15.8,5317.0,1.5,94462,81310.0
7,9,8,General Motors,225000,8,166380,9.2,9427.0,-2.7,221690,52968.0
8,10,9,AT&T,268540,10,163786,11.6,12976.0,-2.8,403821,255679.0
9,11,10,Ford Motor,201000,9,151800,1.5,4596.0,-37.7,237951,46349.0

In [31]:
df.sort_values(by='profitschange',ascending=False).head(10)

,id,rank,name,employees,previousrank,revenues,revenuechange,profits,profitschange,assets,marketvalue
490,492,491,Liberty Media,3626,525,5276,10.0,680.0,962.5,31377,13055.0
105,107,106,Kraft Heinz,41000,153,26487,44.4,3632.0,472.9,120480,110528.0
280,282,281,Baxter International,48000,286,10163,2.0,4965.0,412.9,15546,28106.0
64,66,65,New York Life Insurance,11320,61,40787,-11.1,1088.1,324.1,287196,NaN
309,311,310,eBay,12600,300,8979,-5.4,7266.0,321.2,23847,36232.0
183,185,184,Goodyear Tire & Rubber,66000,169,15158,-7.8,1264.0,311.7,16511,9070.0
446,448,447,Dana Holding,24900,428,5826,-3.9,640.0,302.5,4860,2783.0
360,362,361,Assurant,14700,275,7532,-27.1,565.4,299.4,29709,5298.0
11,13,12,Amazon.com,341400,18,135987,27.1,2371.0,297.8,83402,423031.0
288,290,289,Huntsman,15000,277,9657,-6.2,326.0,250.5,9189,5880.0