In [1]:
import pandas as pd
import numpy as np

In [15]:
file_path = "/Users/godwinvasanthsamueldhinakar/EDA/F500.csv"

df= pd.read_csv(file_path,sep=';')
print('**************************************************')
print(df.info())

**************************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             500 non-null    int64
 1   rank           500 non-null    int64
 2   name           500 non-null    object
 3   employees      500 non-null    object
 4   previousrank   492 non-null    float64
 5   revenues       500 non-null    object
 6   revenuechange  500 non-null    object
 7   profits        500 non-null    object
 8   profitschange  500 non-null    object
 9   assets         500 non-null    object
 10  marketvalue    500 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 43.1+ KB
None

In [3]:
df.head(10)

,id,rank,name,employees,previousrank,revenues,revenuechange,profits,profitschange,assets,marketvalue
0,2,1,Walmart,"2,300,000",1.0,"$485,873",0.8%,"$13,643.0",-7.2%,"$198,825","$218,619"
1,3,2,Berkshire Hathaway,"367,700",4.0,"$223,604",6.1%,"$24,074.0",0.0%,"$620,854","$411,035"
2,4,3,Apple,"116,000",3.0,"$215,639",-7.7%,"$45,687.0",-14.4%,"$321,686","$753,718"
3,5,4,Exxon Mobil,"72,700",2.0,"$205,004",-16.7%,"$7,840.0",-51.5%,"$330,314","$340,056"
4,6,5,McKesson,"68,000",5.0,"$192,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"
5,7,6,UnitedHealth Group,"230,000",6.0,"$184,840",17.7%,"$7,017.0",20.7%,"$122,810","$157,793"
6,8,7,CVS Health,"204,000",7.0,"$177,526",15.8%,"$5,317.0",1.5%,"$94,462","$81,310"
7,9,8,General Motors,"225,000",8.0,"$166,380",9.2%,"$9,427.0",-2.7%,"$221,690","$52,968"
8,10,9,AT&T,"268,540",10.0,"$163,786",11.6%,"$12,976.0",-2.8%,"$403,821","$255,679"
9,11,10,Ford Motor,"201,000",9.0,"$151,800",1.5%,"$4,596.0",-37.7%,"$237,951","$46,349"

In [16]:
df['rev']=pd.to_numeric(df['revenues'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df['prof']=pd.to_numeric(df['profits'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df['asset']=pd.to_numeric(df['assets'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df['marketval']=pd.to_numeric(df['marketvalue'].str.replace(',', '').str.replace('$', ''),errors='coerce')
df.drop(['revenues','profits','assets','marketvalue'],axis=1,inplace=True)

In [17]:
df.head(10)

,id,rank,name,employees,previousrank,revenuechange,profitschange,rev,prof,asset,marketval
0,2,1,Walmart,"2,300,000",1.0,0.8%,-7.2%,485873,13643.0,198825,218619.0
1,3,2,Berkshire Hathaway,"367,700",4.0,6.1%,0.0%,223604,24074.0,620854,411035.0
2,4,3,Apple,"116,000",3.0,-7.7%,-14.4%,215639,45687.0,321686,753718.0
3,5,4,Exxon Mobil,"72,700",2.0,-16.7%,-51.5%,205004,7840.0,330314,340056.0
4,6,5,McKesson,"68,000",5.0,6.2%,53.0%,192487,2258.0,56563,31439.0
5,7,6,UnitedHealth Group,"230,000",6.0,17.7%,20.7%,184840,7017.0,122810,157793.0
6,8,7,CVS Health,"204,000",7.0,15.8%,1.5%,177526,5317.0,94462,81310.0
7,9,8,General Motors,"225,000",8.0,9.2%,-2.7%,166380,9427.0,221690,52968.0
8,10,9,AT&T,"268,540",10.0,11.6%,-2.8%,163786,12976.0,403821,255679.0
9,11,10,Ford Motor,"201,000",9.0,1.5%,-37.7%,151800,4596.0,237951,46349.0